version: "3.4"
services:
   tracly-db:
      image: mcr.microsoft.com/mssql/server
      container_name: tracly_db
      user: root
      volumes:
         - ~docker-volumes/tracly-db-server:/var/opt/mssql/data
      environment:
         SA_PASSWORD: "${DB_PW}"
         ACCEPT_EULA: "Y"
      ports:
         - "1434:1433"
      networks:
         - tracly-network
   tracly-api:
      build:
         context: .
         dockerfile: ./API/Dockerfile
      ports:
         - 5000:5000
      depends_on:
         - tracly-db
      env_file:
      - ./../.env
      networks:
         - tracly-network
volumes:
   tracly-db-server:
networks:
  tracly-network:
    driver: bridge