version: "3.4"
services:
   tracly-db:
      container_name: tracly_db
      image: mcr.microsoft.com/mssql/server
      user: root
      volumes:
         - ~docker-volumes/tracly-db-server:/var/opt/mssql/data
      env_file:
      - ./../.env
      environment:
         MSSQL_SA_PASSWORD: $DB_PW
         ACCEPT_EULA: "Y"
      ports:
         - "1434:1433"
      networks:
         - tracly-network
volumes:
   tracly-db-server:
networks:
  tracly-network:
    driver: bridge
